services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./config:/app/config
      - sqlite_data:/data
    environment:
      - MIRO_DATABASE_URL=sqlite:////data/app.db
      - DB_URL=sqlite:////data/app.db
      - RUN_ALEMBIC=false

  client:
    build:
      context: .
      dockerfile: ./web/client/Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - VITE_BACKEND_URL=http://backend:8000

volumes:
  sqlite_data:
