appName: 'Quick Tools'
sdkVersion: SDK_V2
sdkUri: 'http://localhost:3000'
boardPicker:
  allowedDomains: []
redirectUris: []
redirectUriForSdk: ''
scopes:
  - boards:read
  - boards:write
icons:
  colored: ''
  outline: ''
